/**
 * Google Drive REST API integration helpers for NagarSetu AI.
 * Uses the user's Google Drive OAuth access token obtained via Firebase Auth popup.
 */

export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  thumbnailLink?: string;
  webViewLink?: string;
  size?: string;
  createdTime?: string;
}

/**
 * Lists image files from the user's Google Drive.
 * We filter for images only so they can be picked for civic issue reporting.
 */
export async function listDriveImages(accessToken: string): Promise<DriveFile[]> {
  const q = "mimeType startswith 'image/' and trashed = false";
  const fields = "files(id, name, mimeType, thumbnailLink, webViewLink, size, createdTime)";
  const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=${encodeURIComponent(fields)}&pageSize=30`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Drive list failed: ${errorText || response.statusText}`);
  }

  const data = await response.json();
  return data.files || [];
}

/**
 * Downloads a file's raw content from Google Drive and returns it as a base64 Data URL.
 */
export async function downloadDriveImageBase64(accessToken: string, fileId: string): Promise<string> {
  const url = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Drive download failed: ${errorText || response.statusText}`);
  }

  const blob = await response.blob();
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      resolve(reader.result as string);
    };
    reader.onerror = () => {
      reject(new Error("Failed to convert downloaded Drive image to base64"));
    };
    reader.readAsDataURL(blob);
  });
}

/**
 * Uploads a markdown report receipt directly to Google Drive as a new file.
 */
export async function uploadReportToDrive(
  accessToken: string,
  filename: string,
  markdownContent: string
): Promise<DriveFile> {
  const boundary = "nagarsetu_multipart_boundary";
  const delimiter = `\r\n--${boundary}\r\n`;
  const close_delim = `\r\n--${boundary}--`;

  const metadata = {
    name: filename,
    mimeType: "text/markdown",
    description: "Official civic defect and triage report generated by NagarSetu AI.",
  };

  const body =
    delimiter +
    "Content-Type: application/json; charset=UTF-8\r\n\r\n" +
    JSON.stringify(metadata) +
    delimiter +
    "Content-Type: text/markdown; charset=UTF-8\r\n\r\n" +
    markdownContent +
    close_delim;

  const url = "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink";

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": `multipart/related; boundary=${boundary}`,
    },
    body: body,
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Drive upload failed: ${errorText || response.statusText}`);
  }

  return await response.json();
}
